"use server";

import { Season } from "@prisma/client";
import prisma from "@/lib/prisma";

/**
 * Creates seeds in databse
 */
export async function generateSeeds() {
  const test = await prisma.seed.createMany({
    skipDuplicates: true,
    data: [
      {
        name: "GreenBeanSeeds",
        season: Season.Spring,
        growthDays: 3,
        reGrowthDays: 2,
        isMultiply: false,
        price: 60,
      },
      {
        name: "PotatoSeeds",
        season: Season.Spring,
        growthDays: 3,
        reGrowthDays: 0,
        isMultiply: true,
        price: 50,
      },
      {
        name: "StrawberrySeeds",
        season: Season.Spring,
        growthDays: 3,
        reGrowthDays: 2,
        isMultiply: true,
        price: 30,
      },
      {
        name: "KaleSeeds",
        season: Season.Spring,
        growthDays: 3,
        reGrowthDays: 0,
        isMultiply: false,
        price: 70,
      },
      {
        name: "ParsnipSeeds",
        season: Season.Spring,
        growthDays: 3,
        reGrowthDays: 0,
        isMultiply: false,
        price: 20,
      },
      {
        name: "RhubarbSeeds",
        season: Season.Spring,
        growthDays: 4,
        reGrowthDays: 0,
        isMultiply: false,
        price: 100,
      },
      {
        name: "CauliflowerSeeds",
        season: Season.Spring,
        growthDays: 3,
        reGrowthDays: 0,
        isMultiply: false,
        price: 80,
      },
      {
        name: "GarlicSeeds",
        season: Season.Spring,
        growthDays: 3,
        reGrowthDays: 0,
        isMultiply: false,
        price: 40,
      },
      {
        name: "MelonSeeds",
        season: Season.Summer,
        growthDays: 4,
        reGrowthDays: 0,
        isMultiply: false,
        price: 80,
      },
      {
        name: "HotPepperSeeds",
        season: Season.Summer,
        growthDays: 3,
        reGrowthDays: 2,
        isMultiply: true,
        price: 40,
      },
      {
        name: "RedCabbageSeeds",
        season: Season.Summer,
        growthDays: 4,
        reGrowthDays: 0,
        isMultiply: false,
        price: 100,
      },
      {
        name: "CornSeeds",
        season: Season.Summer,
        growthDays: 4,
        reGrowthDays: 2,
        isMultiply: false,
        price: 150,
      },
      {
        name: "TomatoSeeds",
        season: Season.Summer,
        growthDays: 3,
        reGrowthDays: 2,
        isMultiply: true,
        price: 50,
      },
      {
        name: "WheatSeeds",
        season: Season.Summer,
        growthDays: 3,
        reGrowthDays: 0,
        isMultiply: false,
        price: 10,
      },
      {
        name: "RadishSeeds",
        season: Season.Summer,
        growthDays: 4,
        reGrowthDays: 0,
        isMultiply: false,
        price: 40,
      },
      {
        name: "HopsSeeds",
        season: Season.Summer,
        growthDays: 3,
        reGrowthDays: 1,
        isMultiply: false,
        price: 60,
      },
      {
        name: "BlueberrySeeds",
        season: Season.Summer,
        growthDays: 4,
        reGrowthDays: 2,
        isMultiply: true,
        price: 80,
      },
      {
        name: "AmaranthSeeds",
        season: Season.Autumn,
        growthDays: 3,
        reGrowthDays: 0,
        isMultiply: false,
        price: 70,
      },
      {
        name: "ArtichokeSeeds",
        season: Season.Autumn,
        growthDays: 3,
        reGrowthDays: 0,
        isMultiply: false,
        price: 30,
      },
      {
        name: "EggplantSeeds",
        season: Season.Autumn,
        growthDays: 2,
        reGrowthDays: 3,
        isMultiply: false,
        price: 20,
      },
      {
        name: "YamSeeds",
        season: Season.Autumn,
        growthDays: 3,
        reGrowthDays: 0,
        isMultiply: true,
        price: 60,
      },
      {
        name: "BokChoySeeds",
        season: Season.Autumn,
        growthDays: 3,
        reGrowthDays: 0,
        isMultiply: false,
        price: 50,
      },
      {
        name: "GrapeSeeds",
        season: Season.Autumn,
        growthDays: 3,
        reGrowthDays: 2,
        isMultiply: false,
        price: 60,
      },
      {
        name: "CranberrySeeds",
        season: Season.Autumn,
        growthDays: 3,
        reGrowthDays: 0,
        isMultiply: true,
        price: 240,
      },
      {
        name: "BeetSeeds",
        season: Season.Autumn,
        growthDays: 3,
        reGrowthDays: 0,
        isMultiply: false,
        price: 20,
      },
      {
        name: "PumpkinSeeds",
        season: Season.Autumn,
        growthDays: 3,
        reGrowthDays: 0,
        isMultiply: false,
        price: 100,
      },
      {
        name: "SunflowerSeeds",
        season: Season.Summer,
        growthDays: 2,
        reGrowthDays: 0,
        isMultiply: true,
        price: 50,
      },
      {
        name: "RiceSeeds",
        season: Season.Spring,
        growthDays: 2,
        reGrowthDays: 0,
        isMultiply: false,
        price: 75,
      },
      {
        name: "CoffeeBeanSeeds",
        season: Season.Spring,
        growthDays: 4,
        reGrowthDays: 2,
        isMultiply: true,
        price: 700,
      },
    ],
  });
}
